name: Access Environment Variable Action
description: Accesses a variable from the environment and prints it.
inputs:
  local-var:
    description: a passed variable
    required: true
runs:
  using: composite
  steps:
    - name: Print local variable
      run: echo "Hello ${{ inputs.local-var }}"
      shell: bash
    - name: Print MY_AWS_REGION
      run: echo "Hello ${{ env.vars.MY_AWS_REGION }}"
      shell: bash
    - name: Print GITHUB_ACTOR
      run: echo "Hello ${{ env.GITHUB_ACTOR }}"
      shell: bash
