name: Main Workflow

on:
  workflow_dispatch

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: greet
        run: |
          echo "Hello ${{ vars.MY_AWS_REGION }}"
          echo "Hello $GITHUB_ACTOR"
          
  custom_env:
    runs-on: ubuntu-latest
    environment: doc
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: greet
        uses: ./.github/actions/access-env-var
        with:
          local-var: my-local-var
